### ISSUE TITLE
Dependency on specific python install in pre-flight

### ISSUE THREAD

**Issue by rothnic** [gamechanger/dusty#433] opened 2015-07-28 18:34 UTC
The preflight seems to perform checks using a specific python install. Where this doesn't work is in the case of using something like miniconda, which exists as an independent python install. Here is the output from running the install script. At the end you can see that I have docker-compose installed.

```
→ bash -c "`curl -L https://github.com/gamechanger/dusty/releases/download/0.4.0-RC1/install.sh`"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   387    0   387    0     0   1460      0 --:--:-- --:--:-- --:--:--  1465
100  1270  100  1270    0     0   2400      0 --:--:-- --:--:-- --:--:-- 16933
Downloading dusty binary
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   379    0   379    0     0   1675      0 --:--:-- --:--:-- --:--:--  1676
100 6139k  100 6139k    0     0  2030k      0  0:00:03  0:00:03 --:--:-- 2373k
Authenticating as super user... needed to setup daemon
Password:
Resetting dusty daemon
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   779  100   779    0     0   2474      0 --:--:-- --:--:-- --:--:--  2480
/Library/LaunchDaemons/com.gamechanger.dusty.plist: Could not find specified service
Testing dusty daemon's preflight...
2015-07-28 13:23:32 INFO:root Starting preflight check
2015-07-28 13:23:32 INFO:root Checking for required executables. PATH is /Users/nroth/.pyenv:./node_modules/.bin:/usr/local/bin:/Users/nroth/.npm:/Users/nroth/.node/bin:/Users/nroth/anaconda/lib:/Users/nroth/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Users/nroth/.bash_it/plugins/available/todo
2015-07-28 13:23:32 INFO:root Checking for existence of git
2015-07-28 13:23:32 INFO:root Checking for existence of rsync
2015-07-28 13:23:32 INFO:root Checking for existence of VBoxManage
2015-07-28 13:23:32 WARNING:py.warnings /tmp/_MEIQbAGLX/dusty/preflight.py:42: UserWarning: Your virtualbox version (4.3.28) deviates from the supported version (4.3.26).

2015-07-28 13:23:32 INFO:root Checking for existence of boot2docker
2015-07-28 13:23:32 INFO:root Checking for existence of docker
2015-07-28 13:23:32 INFO:root Checking for existence of docker-compose
Traceback (most recent call last):
  File "/Users/nroth/anaconda/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/Users/nroth/anaconda/lib/python2.7/site-packages/compose/cli/main.py", line 10, in <module>
    from docker.errors import APIError
  File "/Users/nroth/anaconda/lib/python2.7/site-packages/docker/__init__.py", line 20, in <module>
    from .client import Client, AutoVersionClient # flake8: noqa
  File "/Users/nroth/anaconda/lib/python2.7/site-packages/docker/client.py", line 23, in <module>
    from . import clientbase
  File "/Users/nroth/anaconda/lib/python2.7/site-packages/docker/clientbase.py", line 4, in <module>
    import requests
  File "/Users/nroth/anaconda/lib/python2.7/site-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Users/nroth/anaconda/lib/python2.7/site-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/Users/nroth/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/Users/nroth/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 31, in <module>
    from .connection import (
  File "/Users/nroth/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 11, in <module>
    from httplib import HTTPConnection as _HTTPConnection, HTTPException
  File "/Users/nroth/anaconda/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/Users/nroth/anaconda/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/Users/nroth/anaconda/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/Users/nroth/anaconda/lib/python2.7/random.py", line 49, in <module>
    import hashlib as _hashlib
  File "/Users/nroth/anaconda/lib/python2.7/hashlib.py", line 138, in <module>
    _hashlib.openssl_md_meth_names)
AttributeError: 'module' object has no attribute 'openssl_md_meth_names'
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/jenkins/jenkins/workspace/DustyRelease/build/dusty/out00-PYZ.pyz/dusty.cli", line 129, in main
  File "/Users/jenkins/jenkins/workspace/DustyRelease/build/dusty/out00-PYZ.pyz/dusty.daemon", line 110, in main
  File "/Users/jenkins/jenkins/workspace/DustyRelease/build/dusty/out00-PYZ.pyz/dusty.preflight", line 121, in preflight_check
dusty.preflight.PreflightException: Preflight Errors:
	Command '['docker-compose', '--version']' returned non-zero exit status 1
Preflight failed; not loading daemon

87:  ~
→ docker-compose --version
docker-compose version: 1.3.3
CPython version: 2.7.10
OpenSSL version: OpenSSL 1.0.1k 8 Jan 2015
```

**Comment by thieman** [comment] 2015-07-28 19:24
We've seen a very similar traceback coming out of Docker Compose before: https://github.com/gamechanger/dusty/issues/416. What are you getting from `which docker-compose`? Dusty is finding a version installed in your Anaconda virtualenv, and I'm wondering whether that is the same one you're running your standalone `--version` command against.

As an option, you can join us on [our public Slack](http://dusty-slackin.herokuapp.com) where it's usually easier to bang out solutions to stuff like this pretty quickly.

**Comment by thieman** [comment] 2015-08-12 02:15
I'm going to go ahead and close this since it seems to be a duplicate of the other issue I linked, please re-open if you'd like to investigate further.

**Closed by thieman** 2015-08-12 02:15 UTC
Labels: kind/question
