### ISSUE TITLE
UnicodeEncodeError caused by bundle description

### ISSUE THREAD

**Issue by torbjornvatn** [gamechanger/dusty#538] opened 2015-08-23 05:17 UTC
I got this error when running ```dusty bundles list```:

```bash
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/jenkins/jenkins/workspace/DustyRelease/build/dusty/out00-PYZ.pyz/dusty.cli", line 151, in main
  File "/Users/jenkins/jenkins/workspace/DustyRelease/build/dusty/out00-PYZ.pyz/dusty.cli", line 116, in _run_payload
  File "/Users/jenkins/jenkins/workspace/DustyRelease/build/dusty/out00-PYZ.pyz/dusty.cli", line 82, in _run_command
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 473: ordinal not in range(128)
```

Since I'm Norwegian i [quickly suspected](http://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20?answertab=active#tab-top) the norwegian letter *ø* in one of my bundle descriptions, and when I removed it the problem went away.

**Comment by thieman** [comment] 2015-08-23 12:07
Ah, the joys of Python2. When we go to fix this, let's make sure to sprinkle some non-ASCII characters among our test fixtures to flush out other errors that could be caused by this.

**Comment by torbjornvatn** [comment] 2015-08-24 07:58
May I suggest: "så æ e trønder æ" :smile:

**Comment by thieman** [comment] 2015-08-24 13:21
It's 9 in the morning and I'm already being trolled in a foreign language, clearly this is going to be a good day. :smile: 

@zacharym any interest in working on this one?

**Comment by thieman** [comment] 2015-08-24 20:29
Debugging this has been a bit interesting. Adding unicode to a bundle description works just fine when running the daemon from source, but produces the error you found when running the daemon from the binary. Still investigating.

**Comment by jsingle** [comment] 2015-09-09 18:28
We can support unicode for things like bundle descriptions. Unicode support for things like app, service, and lib names isn't feasible because of restrictions our dependencies, like docker-compose

**Comment by torbjornvatn** [comment] 2015-09-09 20:59
I think that would suffice, because I try to use non Norwegian characters in names and paths for the same reason.
But the description is convenient to write in Norwegian (at least at my current job)

**Comment by paetling** [comment] 2016-02-11 21:32
This pr implemented what @jsingle talked about on Sep 9th: https://github.com/gamechanger/dusty/pull/576.

**Comment by paetling** [comment] 2016-02-11 21:35
Dusty currently allows unicode in your <file_name>.yml specs contents, but you cannot use unicode in the <file_name> itself.   This fixes @torbjornvatn's issue so going to close this issue.

**Closed** 2016-02-11 21:35 UTC
Labels: exp/proficient, kind/bug
