### ISSUE TITLE
Dusty should cleanup unused volumes and images

### ISSUE THREAD

**Issue by paetling** [gamechanger/dusty#622] opened 2016-01-26 20:50 UTC
Yesterday I ran into a problem where I ran out of disk space on my Virtualbox dusty vm.  The problem seems to be that I had a bunch of left over containers and images from what I assume is the dusty testing process.   I used the following command to cleanup this leftover junk:
```
docker rm $(docker ps -aq)
docker rmi $(docker images -q)
```

This seems like something that dusty should be handling / cleaning up itself.  

Thoughts?

**Comment by thieman** [comment] 2016-01-26 20:53
Is this a dupe of https://github.com/gamechanger/dusty/issues/603?

**Comment by paetling** [comment] 2016-01-26 20:59
Seems to be very similar yes.  Do we handle removing containers correctly?  Both were issues for me.

**Closed** 2016-02-11 17:57 UTC
Labels: exp/novice, kind/bug
